name: release

on:
  push:
    tags:
      - '*'
      - '**'

env:
  goversion: 1.17

jobs:
  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: run go 1.17
        uses: actions/setup-go@v2
        with: 
          go-version: ${{ env.goversion }}

      - name: checkout code
        uses: actions/checkout@v2

      - name: execute tests
        shell: bash
        run: go test -race -cover ./...

  release:
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    needs:
      - unit-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.goversion }}

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist