name: unit-tests

on:
  push:
    branches:
      - '*'
      - '**'
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - ".github"
      - ".goreleaser.yml"
      - "*.yml"
      - "*.yaml"
      - "*.json"
      - "*.md"

env:
  goversion: 1.17

jobs:
  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      COVER_FILE: coverage.txt
    steps:
      - name: run go ${{ env.goversion }}
        uses: actions/setup-go@v2
        with: 
          go-version: ${{ env.goversion }}

      - name: checkout code
        uses: actions/checkout@v2

      - name: execute tests
        shell: bash
        run: go test -race -coverprofile=$COVER_FILE -covermode=atomic $(go list ./...)

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ env.CODECOV_TOKEN }}
          env_vars: OS,GOLANG
          fail_ci_if_error: true
          files: ${{ env.COVER_FILE }}
          flags: unittests